### ISSUE TITLE
Interaction with bullet threading plugin

### ISSUE THREAD

**Issue by jsanz** [nmartin84/logseq-nord#4]
Unfortunately the dark theme is clashing with the [bullet threading](https://github.com/pengx17/logseq-plugin-bullet-threading) plugin. This is not the case with other themes.

Nord theme:

![image](https://user-images.githubusercontent.com/188264/197796674-76bd113f-1472-4598-8bbc-8e89a620be3c.png)

Dracula theme:

![image](https://user-images.githubusercontent.com/188264/197797029-c87e00ff-925d-493b-b1ac-48636ad146b4.png)

Mia theme:

![image](https://user-images.githubusercontent.com/188264/197797148-d3d3c0a1-449b-448e-a609-d9e0257d8189.png)

**Comment by nmartin84** [comment]
Hey @jsanz - you may want to check out the https://github.com/nmartin84/logseq-flow theme, which includes a color palette for Nord. This repo hasn't been maintained in some time, but if you plan to stick with this theme let me know and i'll add this to my things to complete.
