### ISSUE TITLE
Move the theme update into a new theme

### ISSUE THREAD

**Issue by necauqua** [nmartin84/logseq-nord#9]
So due to certain reasons I've reinstalled logseq and all the things, including this theme.

Next thing I find is this:
 - background images (which I'm not against, but I personally don't like them - and the dark theme one seems.. bad? like it's broken probably maybe, it's not what is on screenshots here)
 - whatever you did to #hashtags (uugghh, that's like actually horrible, eew)
 - broken `code blocks` (#8) - since they were not broken previously you've seem to change (incorrectly) the font family
 - a few other changes in terms of colors and whatnot

The last point is not even something I necessarily dislike (that pink purple is cool; but the page background is not a nord background even), but the theme update mechanism is there to fix broken things and style new things added by the app and so on, but you've seem to completely change the theme - enough (it's not just fixes) for it to be a separate one, and the original one that I liked more (slightly, at least the tags) is now gone - unless I go through the trouble of recovering it from git history

**Comment by nmartin84** [comment]
Closing - sorry if you do not like the theme style, but you are free to use whatever other theme you like, or you can fork this theme and make your own modifications to suite your needs.

**Comment by necauqua** [comment]
> you do not like the theme style

Ehh, the point was not if I like or I don't like it, the point was that once the theme was one thing - and then suddenly it became another - not something that should happen with theme updates, making a whole another teme should come with naming it differently and having it be separate.

> fork this theme

yeah I figured it would likely end with this
